title: fitzKhayyam
email: daniel.allington@kcl.ac.uk
description: >- 
  An online archive of the first five editions of Edward FitzGerald's translation
  of the <i>Rubayat of Omar Khayyam</i>.
baseurl: "" 
url: "http://fitzkhayyam.netlify.app" 
github_username:  daniel-allington

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
collections:
  stanzas:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - python
  
